[package]
name = "drivingsim"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "drivingsim_py",
]

[dependencies]
anyhow = "1.0.95"
ggez = "0.9.3"
nalgebra = "0.33.2"
thiserror = "2.0.11"
